volumes:
  search-v2-evaluator-tmp:
  search-v2-evaluator-node-modules:

x-search-v2-evaluator: &search-v2-evaluator
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: search-v2-evaluator
  tty: true
  stdin_open: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - search-v2-evaluator-tmp:/govuk/search-v2-evaluator/tmp
    - search-v2-evaluator-node-modules:/govuk/search-v2-evaluator/node_modules
  working_dir: /govuk/search-v2-evaluator

services:
  search-v2-evaluator-lite:
    <<: *search-v2-evaluator

  search-v2-evaluator-app: &search-v2-evaluator-app
    <<: *search-v2-evaluator
    depends_on:
      - nginx-proxy
      - search-api-v2-app
    environment:
      VIRTUAL_HOST: search-v2-evaluator.dev.gov.uk
      RAILS_DEVELOPMENT_HOSTS: "search-v2-evaluator.dev.gov.uk,search-v2-evaluator"
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails server --restart
