version: '3.7'

volumes:
  govuk-chat-tmp:
  govuk-chat-node-modules:

x-govuk-chat: &govuk-chat
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-chat
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - govuk-chat-tmp:/govuk/govuk-chat/tmp
    - govuk-chat-node-modules:/govuk/govuk-chat/node_modules
  working_dir: /govuk/govuk-chat

services:
  govuk-chat-lite:
    <<: *govuk-chat
    depends_on:
      - opensearch-2
      - postgres-13
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/govuk-chat"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/govuk-chat-test"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      OPENSEARCH_URL: http://opensearch-2:9200

  govuk-chat-app:
    <<: *govuk-chat
    depends_on:
      - govuk-chat-css
      - govuk-chat-worker
      - nginx-proxy
      - postgres-13
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/govuk-chat"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: govuk-chat.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/dev web

  govuk-chat-css:
    <<: *govuk-chat
    command: bin/dev css

  govuk-chat-worker:
    <<: *govuk-chat
    depends_on:
      - redis
      - postgres-13
    environment:
      REDIS_URL: redis://redis
      DATABASE_URL: "postgresql://postgres@postgres-13/govuk-chat"
    command: bin/dev worker

  govuk-chat-queue-consumer:
    <<: *govuk-chat
    depends_on:
      - opensearch-2
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      OPENSEARCH_URL: http://opensearch-2:9200
    command: bin/dev queue_consumer
