x-search-api-v2: &search-api-v2
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: search-api-v2
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - search-api-v2-tmp:/govuk/search-api-v2/tmp
    - root-home:/root
    # Mount the host's gcloud config directory into the container so that the app can use
    # Application Default Credentials (required to use Discovery Engine locally)
    - "~/.config/gcloud:/root/.config/gcloud:delegated"
  working_dir: /govuk/search-api-v2

volumes:
  search-api-v2-tmp:

services:
  search-api-v2-lite:
    <<: *search-api-v2
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      PUBLISHED_DOCUMENTS_MESSAGE_QUEUE_NAME: search_api_v2_published_documents
      DISCOVERY_ENGINE_DATASTORE_BRANCH: none
      DISCOVERY_ENGINE_SERVING_CONFIG: none

  search-api-v2-app:
    <<: *search-api-v2
    depends_on:
      - nginx-proxy
      - rabbitmq
      - search-api-v2-document-sync-worker
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq"
      PUBLISHED_DOCUMENTS_MESSAGE_QUEUE_NAME: "search_api_v2_published_documents"
      RAILS_DEVELOPMENT_HOSTS: "search-api-v2.dev.gov.uk,search-api-v2-app"
      VIRTUAL_HOST: "search-api-v2.dev.gov.uk"
      BINDING: "0.0.0.0"
      # The fully qualified ID of the datastore branch and engine on the Discovery Engine dev
      # environment (required to use Discovery Engine locally, can be set on `govuk-docker up`
      # invocation or permanently in your local environment).
      #
      # e.g. "projects/search-api-v2-dev/locations/global/collections/default_collection/dataStores/
      #       local-my-name/branches/default_branch"
      DISCOVERY_ENGINE_DATASTORE_BRANCH: "${DISCOVERY_ENGINE_DATASTORE_BRANCH}"
      # e.g. "projects/search-api-v2-dev/locations/global/collections/default_collection/dataStores/
      #       local-my-name/servingConfigs/default_serving_config"
      DISCOVERY_ENGINE_SERVING_CONFIG: "${DISCOVERY_ENGINE_SERVING_CONFIG}"
    expose:
      - "3000"
    command: bin/rails server --restart

  search-api-v2-document-sync-worker:
    <<: *search-api-v2
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq"
      PUBLISHED_DOCUMENTS_MESSAGE_QUEUE_NAME: "search_api_v2_published_documents"
      # The fully qualified ID of the datastore branch and serving config on the Discovery Engine
      # dev environment (required to use Discovery Engine locally, can be set on `govuk-docker up`
      # invocation or permanently in your local environment).
      #
      # e.g. "projects/search-api-v2-dev/locations/global/collections/default_collection/dataStores/
      #       local-my-name/branches/default_branch"
      DISCOVERY_ENGINE_DATASTORE_BRANCH: "${DISCOVERY_ENGINE_DATASTORE_BRANCH}"
      # e.g. "projects/search-api-v2-dev/locations/global/collections/default_collection/dataStores/
      #       local-my-name/servingConfigs/default_serving_config"
      DISCOVERY_ENGINE_SERVING_CONFIG: "${DISCOVERY_ENGINE_SERVING_CONFIG}"
    command: bin/rake document_sync_worker:run
